### ISSUE TITLE
[new] contract interfaces violations

### ISSUE THREAD

**Issue by kalessil** [kalessil/phpinspectionsea#14]
Original link: https://bitbucket.org/kalessil/phpinspectionsea/issues/200/new-inspections-contract-interfaces
Author: @kalessil

See https://youtrack.jetbrains.com/issue/WI-30800

**Comment by rentalhost** [comment]
**Todo:**

* [ ] Check if method annotate `@thrown`;
* [ ] Check if method throws an exception by itself;
* [ ] Check if method don't treats an exception thrown by inner methods;

For each thrown exception, check if it is annotated on original signature allows that (from interface or parent class).

**Comment by kalessil** [comment]
Closing this:
- PhpDoc is involved
- the desired reporting should be possible to archive by configuring existing inspections
